name: v2026-07-02
services:
  bitwarden:
    depends_on:
      - db
    env_file:
      - .env
      - path: ./flags.env
        required: false
    image: ghcr.io/bitwarden/lite@sha256:11b0a7bd63686ce2563d8b78ad591f7e0ee9e350cd1f79ad6f11c9ce3dbb01f3 # 2026.8.0
    restart: "no"
    ports:
      - ${VAULT_HOST_PORT}:8443
      - ${VAULT_HOST_INSECURE_PORT}:8080
    volumes:
      - ./${BW_SSL_CERT}:/etc/bitwarden/${BW_SSL_CERT}
      - ./${BW_SSL_KEY}:/etc/bitwarden/${BW_SSL_KEY}

  db:
    environment:
      MARIADB_USER: ${BW_DB_USERNAME}
      MARIADB_PASSWORD: ${BW_DB_PASSWORD}
      MARIADB_DATABASE: ${BW_DB_DATABASE}
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    image: mariadb@sha256:628f228f0fd5913a220438693576b29b6fe4dc1fa0a1298c0e98579fae28635f # 12
    restart: "no"
    volumes:
      - data:/var/lib/mysql
    ports:
      - ${BW_DB_PORT}:${BW_DB_PORT}

volumes:
  bitwarden:
  data:
