name: v2026-07-02
services:
  bitwarden:
    depends_on:
      - db
    env_file:
      - .env
      - path: ./flags.env
        required: false
    image: ghcr.io/bitwarden/lite@sha256:ca1007fb3a8e973692ca1b92b87e52d2101976ef9bdf76d8639682485a5866dc # 2026.7.2
    restart: "no"
    ports:
      - ${VAULT_HOST_PORT}:8443
      - ${VAULT_HOST_INSECURE_PORT}:8080
    volumes:
      - ./${BW_SSL_CERT}:/etc/bitwarden/${BW_SSL_CERT}
      - ./${BW_SSL_KEY}:/etc/bitwarden/${BW_SSL_KEY}

  db:
    environment:
      MARIADB_USER: ${BW_DB_USERNAME}
      MARIADB_PASSWORD: ${BW_DB_PASSWORD}
      MARIADB_DATABASE: ${BW_DB_DATABASE}
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    image: mariadb@sha256:dd9b303aed4f4890ed09f766d8ca9ddfd176c0c6f6267feff53b3192ec65a979 # 12
    restart: "no"
    volumes:
      - data:/var/lib/mysql
    ports:
      - ${BW_DB_PORT}:${BW_DB_PORT}

volumes:
  bitwarden:
  data:
